modLoader = "javafml"
loaderVersion = "[36,)"
license = "All rights reserved"
[[mods]]
modId = "h3ks_tools"
version = "${file.jarVersion}"
displayName = "H3K's Tools Mod"
# logoFile = "h3ks_tools.png"
authors = "henners3k"
description = "Adds some additional tools and stuff to minecraft!"

[[dependencies.h3ks_tools]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.h3ks_tools]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
